# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration Tests

on:
  push:
    branches:    
      - '*'           # matches every branch that doesn't contain a '/'
      - '*/*'         # matches every branch containing a single '/'
      - '**'          # matches every branch
      - '!front-end'  # excludes front-end
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./back-end

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
          touch .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_CLUSTER=${{ secrets.DB_CLUSTER }} >> .env
          echo CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          cat .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './back-end/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:integration
